# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - "bin/**/*"
    - "db/migrate/**/*"

Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'config/routes.rb'
    - 'lib/archangel/testing_support/**/*.rb'
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

Metrics/LineLength:
  Max: 80

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: leading

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
