default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/archangel_sample_development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/archangel_sample_test.sqlite3

production:
  <<: *default
  database: archangel_sample_production
  url: <%= ENV["DATABASE_URL"] %>
